### ISSUE TITLE
Moving multiple files doesn't work

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-files#295]
@frankrousseau reported that when moving multiple files, it stops at the first one.

**Comment by frankrousseau** [comment]
It looks like the selection of multiple file is not properly handled.

**Comment by clochix** [comment]
@frankrousseau this problem seems to have been fixed, could you try ?

**Comment by frankrousseau** [comment]
It's still broken on my Cozy. Does it work for you @clochix?

**Comment by clochix** [comment]
Yes it works. I select some files by clicking on their line, which become light blue (IMHO we should use a darker color, because it's hard to distinguish selected lines on low contrast displays) and then I can move them to another folder.

**Comment by poupotte** [comment]
@frankrousseau this issue is still relevant ?

**Comment by frankrousseau** [comment]
I think it happens when you move files two times in a row. There is a bug with the selection.

**Comment by jsilvestre** [comment]
I think this is a duplicate of https://github.com/cozy/cozy-files/issues/382, so I close it.
